[package]
name = "pew"
version = "0.1.0"
authors = ["Akshay Nanavati <akshay.nanavati1@gmail.com>"]
repository = "https://github.com/akshaynanavati/pew"
readme = "README.md"
keywords = ["benchmark"]
license = "Apache-2.0"
