[package]
name = "pew"
description = "A benchmarking library for Rust based on google/benchmark"
version = "0.1.2"
authors = ["Akshay Nanavati <akshay.nanavati1@gmail.com>"]
repository = "https://github.com/akshaynanavati/pew"
readme = "README.md"
keywords = ["benchmark"]
license = "Apache-2.0"
